name: Create release and Publish
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install the dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Setup git - user email
        run: git config user.email "${{ secrets.USER_EMAIL }}"

      - name: Setup git - user name
        run: git config user.name "Mani Reddy"

      - name: Increment version (patch)
        id: updated_npm_version
        run: |
          # Increment version and create tag
          npm version patch -m "Updated to v%s"
          # Push the commit and tag back to the repository
          git push origin main --tags

      - name: Publish VSIX to Marketplace
        run: vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.updated_npm_version.outputs.new_version }}
          generate_release_notes: true
          make_latest: true
          files: |
            *.vsix
